#!/bin/zsh

i=0
for q in queue/*
do
    grep -F '"original"' "$q" | grep -E -o '"Minecraft.*"' | tr -d '"' | while read f
    do
        grep -F "$f" -r history -q || i=$((i + 1))
    done
done

echo $i

