#!/usr/bin/env python3

import json
import subprocess

with open('src/remaining.json', 'r') as f:
    rems = json.load(f)

i = 0
for r in rems:
    res = subprocess.run(
        ['grep', '-F', r, '-r', 'history', '-q']
    )
    if res.returncode:
        i += 1

print(i)

