#!/usr/bin/env dash

[ -d .venv ] && rm -r .venv
python3 -m venv .venv
. .venv/bin/activate
pip3 install -r requirements.txt
command -v ffmpeg || brew install ffmpeg
deactivate

echo 'successfully installed .venv'
