# command line
BAD_COMMAND_LINE_ARGS = 1

# remaining
FILES_REMAINING = 2
MISSING_REMAINING = 3

# config path folders
NO_SOURCE_FOLDER = 4
NO_RENAMES_FOLDER = 5
NO_DESTINATION_FOLDER = 6

# queue
NO_QUEUE = 7
EMPTY_QUEUE = 8

# file structure folders
NO_HISTORY_FOLDER = 9
NO_ERRORS_FOLDER = 10

# treatment
TREATMENT_ERROR = 11

# config swapping
NO_CONFIGS_FOLDER = 12
NO_CONFIG = 13
NO_CURRENT_CONFIG = 14
NO_CONFIG_CONF_FILE = 15
NO_CONFIG_REMAINING = 16

# config errors
CONFIG_MISSING_SOURCE = 17
CONFIG_MISSING_RENAMES = 18
CONFIG_MISSING_DESTINATION = 19
