name: run-tests
run-name: Run mve tests
on:
  pull_request:
    branches:
      - main
jobs:
  Run-Tests:
    runs-on: macos-latest
    steps:
      - name: install ssh keys
        env:
          PRIVATE: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          [ -d ~/.ssh ] || mkdir ~/.ssh
          printf '%s\n' "$PRIVATE" >> ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
      - name: install mve-tests
        run: |
          git clone git@github.com:z5267282/mve-tests.git
          cd mve-tests
          ./setup
          cd ..
      - name: install mve
        env:
          BRANCH: ${{ github.head_ref }}
        run: |
          git clone git@github.com:z5267282/mve.git
          cd mve
          git fetch origin
          git checkout "$BRANCH"
          ./setup
          cd ..
      - name: run tests
        run: |
          cd mve-tests
          ./run --debug
